insert into player ( id, elo, name) values(1, 1500, "Real Madrid");
insert into player ( id, elo, name) values(2, 1500, "Barcelona");
insert into player ( id, elo, name) values(3, 1500, "Athletico Madrid");
insert into player ( id, elo, name) values(4, 1500, "Inter Milan");
insert into player ( id, elo, name) values(5, 1500, "AS Roma");
insert into player ( id, elo, name) values(6, 1500, "Juventus");
insert into player ( id, elo, name) values(7, 1500, "AC Milan");
insert into player ( id, elo, name) values(8, 1500, "Sevilla");
insert into player ( id, elo, name) values(9, 1500, "Man. United");
insert into player ( id, elo, name) values(10, 1500, "Chelsea");
insert into player ( id, elo, name) values(11, 1500, "Man. City");
insert into player ( id, elo, name) values(12, 1500, "Liverpool");
insert into player ( id, elo, name) values(13, 1500, "Tottenham");
insert into player ( id, elo, name) values(14, 1500, "Arsenal");
insert into player ( id, elo, name) values(15, 1500, "PSG");
insert into player ( id, elo, name) values(16, 1500, "Nice");
insert into player ( id, elo, name) values(17, 1500, "Lyon");
insert into player ( id, elo, name) values(18, 1500, "Bayern Munchen");
insert into player ( id, elo, name) values(19, 1500, "Dortmund");
insert into player ( id, elo, name) values(20, 1500, "RB Leipzig");